### ISSUE TITLE
Don't close context menu on mouseleave

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/blocks#10]
This is the same for the current editor and it led to some confusion. While every other context menu stays open when the cursor leaves the area, the block context menu closes. I'd suggest having a consistent behavior and only close it when you click elsewhere.

I guess this is related to displaying/hiding the drag handle and ↓ button. If it's not possible at all, maybe a small area around the context menu could help making it less frustrating.

![2020-10-28 11-21-32 2020-10-28 11_22_53](https://user-images.githubusercontent.com/7975568/97423709-f1640580-190f-11eb-9164-767031e73b3c.gif)

**Comment by bastianallgeier** [comment]
✅
