### ISSUE TITLE
FieldsetGroups open or closed

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#14]
Can the fieldset groups later be defined which are open and which are closed? Would make sense when having a lot of fields

<img width="475" alt="Bildschirmfoto 2020-10-28 um 11 12 04" src="https://user-images.githubusercontent.com/2178466/97424625-46544b80-1911-11eb-926b-75584ca6b648.png">

**Comment by bastianallgeier** [comment]
That should be easy to implement.

**Comment by bastianallgeier** [comment]
You will be able to close groups by default in the next alpha with `open: false`
