### ISSUE TITLE
Adding a layout scrolls to the top

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/blocks#17]
The page scrolls to the top when adding a layout to a layout field with one possible layout.
This does not happen when there are multiple layouts and the layout selector is [not skipped](https://github.com/getkirby/blocks/issues/9).

![scroll-to-top](https://user-images.githubusercontent.com/7975568/97540234-a1df1180-19c3-11eb-8eb2-b1de48c97761.gif)

**Comment by afbora** [comment]
✅
