### ISSUE TITLE
Create new page with layout field - Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by iskrisis** [getkirby/blocks#18]
Tested with fresh Starterkit + replaced Kirby folder + deleted media. 

![Screen Shot 2020-10-29 at 18 19 58](https://user-images.githubusercontent.com/4954323/97609443-eabeb680-1a13-11eb-8c91-1e1d00ad831d.png)

Page can be created when doing `type: blocks` first then chaning it to `type: layout`  and after that everything works.

I've tried different things not sure how to debug it. But is it somehow related to https://github.com/getkirby/blocks/issues/1 because it's impossible simply modify page blueprint of already created pages. Does `type: layout` require some initial setup? (it seems to just create `test: []` in content).

**Comment by afbora** [comment]
✅

**Comment by iskrisis** [comment]
Can confirm this fixes problem.
