### ISSUE TITLE
The field type "blocks" does not exist

### ISSUE THREAD

**Issue by aristotheme** [getkirby/blocks#21]
I got this error :(

**Comment by afbora** [comment]
Did you download it from here? 
Also did you delete the cache and media folder?

https://github.com/getkirby/kirby/archive/feature/blocks.zip

**Comment by aristotheme** [comment]
I installed Plainkit and upload https://github.com/getkirby/kirby/archive/feature/blocks.zip to kirby folder.

**Comment by aristotheme** [comment]
Ahhh okay after I deleted files from media folder now it works well. Thank you so much Ahmet 💯

**Comment by afbora** [comment]
Great! 🎉 You can close the issue.
