### ISSUE TITLE
Broken layout after saving

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#23]
In the latest version, saving in the layout destroys the layout after the page is refreshed. Below is a little video. Edit: seems not only affecting Layouts, generally in the content file there are some parts missing as I can see?

![layouter](https://user-images.githubusercontent.com/2178466/97903833-e827ce00-1d3f-11eb-8b50-1ed69a43aecb.gif)

**Comment by afbora** [comment]
✅

**Comment by Werbschaft** [comment]
That fixed it 👍🏻

**Comment by afbora** [comment]
Thanks for testing @Werbschaft 🙏

**Comment by Werbschaft** [comment]
You're welcome @afbora  😃

**Comment by bastianallgeier** [comment]
@afbora thanks for taking care of that! <3
