### ISSUE TITLE
Keyboard-only (and touch-screen) use of Blocks UI

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/blocks#28]
This potentially overlaps with the ongoing UI considerations you mentioned in #25, but I thought to create a separate issue as it addresses a different need:

It would be great to see Blocks support keyboard navigation, as was possible with the Builder plugin (all settings and content could be reached by tabbing through; except for rearranging block order and collapse/expand).

On a related note, using Blocks with touch-screen devices is currently limited by the "configuration arrow" being hidden unless hovered.

**Comment by iskrisis** [comment]
I would bet keyboard navigation is super niche in percents of users maximum. So personally it would be pretty low urgency for me/my users.

The touch on the other hand can be important sometimes. But i think thats just matter of time.

**Comment by bastianallgeier** [comment]
✅
