### ISSUE TITLE
Let the layout object know which layout is selected

### ISSUE THREAD

**Issue by flokosiol** [getkirby/blocks#34]
I have a custom grid system where the width of the columns is defined on the wrapping container like this:

```html
<div class="grid grid--33-66">
  <div class="column"></div>
  <div class="column"></div>
  <div class="column"></div>
  <div class="column"></div>
</div>
```

Therefore it would be awesome if the layout object would know about its selected layout. It might be useful if we could add a key to the layout definitions in the blueprint like this:

```yml
fields:
  layout: 
    type: layout
    layouts:
      100: "1/1"
      50: "1/2, 1/2"
      33-66: "1/3, 2/3"
      66-33: "2/3, 1/3"
      33: "1/3, 1/3, 1/3"
```

… and then come back to it in the template with `$layout->key()`

```php
<?php foreach ($page->layout()->toLayouts() as $layout): ?>
  <section class="grid grid--<?= $layout->key() ?>" id="<?= $layout->id() ?>">
    <?php foreach ($layout->columns() as $column): ?>
    <div class="column" style="--span:<?= $column->span() ?>">
      …
    </div>
    <?php endforeach ?>
  </section>
  <?php endforeach ?>
```

So far I found the workaround to use `A::join($layout->columns()->pluck('span'), '-')` which results at least in `8-4` but feels a bit hacky. 

Another option would be to allow custom layout methods.

**Comment by bastianallgeier** [comment]
This is going to be super easy once there are layout settings. They are coming in the next few days.

**Comment by bastianallgeier** [comment]
✅
