### ISSUE TITLE
Writing letters quickly results in errors

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#36]
If you write quickly, the last letter disappears. Just quickly write a sequence of letters in a field in the drawer. For example:

st, ar, fh

![letters](https://user-images.githubusercontent.com/2178466/98927570-ff518300-24d8-11eb-910d-835dfe45e893.gif)

**Comment by medienbaecker** [comment]
I tried to reproduce this but it works fine for me on macOS with the latest Chrome. So I think it would be helpful to post your setup.

![Screenshot-12-11-2020_12-54-21](https://user-images.githubusercontent.com/7975568/98937174-4eea7b80-24e6-11eb-8fa3-ae20caa1f803.gif)

**Comment by Werbschaft** [comment]
@medienbaecker use this and it can be reproduced: https://github.com/getkirby/blocks/issues/35

**Comment by medienbaecker** [comment]
Ah, I see. So it only happens in nested blocks. I could reproduce that.

**Comment by bastianallgeier** [comment]
Nested blocks are not really implemented correctly at all right now.

**Comment by bastianallgeier** [comment]
This is basically the same problem: https://github.com/getkirby/blocks/issues/35
