### ISSUE TITLE
Better way to remove layouts

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#37]
Currently it is very difficult to delete a layout that was created incorrectly. Because a click always opens the dialog and so it is hardly possible to remove the layout unless you know how (click on the side of the empty space). In addition, it might also make sense, as with the normal blocks, that there is a button at the top with "delete all"?

Edit: I just noticed that moving entire rows is also quite problematic

![delete-layout](https://user-images.githubusercontent.com/2178466/98928777-79ced280-24da-11eb-9983-5e1a6e9b2502.gif)

**Comment by bastianallgeier** [comment]
✅
