### ISSUE TITLE
Reordering of blocks still slightly wobbly and unclear

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#38]
First of all, it's super awesome that the blocks can now also be moved in the layout, a great relief. But somehow it works, but it's still a bit bumpy. I hope you can see it in the GIF.

1. You have to put the block at the top so that it works although the area is also gray elsewhere and suggests that you can let go there.

2. When moving and placing the heights shift permanently and the whole layout wobbles as a result.

![reorder](https://user-images.githubusercontent.com/2178466/98929658-c36bed00-24db-11eb-82a9-2003ebf58415.gif)

**Comment by bastianallgeier** [comment]
✅  It's a lot smoother since yesterday's release.
