### ISSUE TITLE
Suggestion: different distances in the layouter

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#40]
Today I showed 2 employees the new layout field for the first time to ask for their opinion as they are our main end users. First of all, huge praise, they were absolutely thrilled! The only thing that both of them noticed negatively is that the delimitation is not really clear with complex layouts. Maybe it would make sense to set distances here? This is of course not a bug, everyone can add it afterwards in their own Panel CSS file, but maybe it is a general improvement?

**Before**
<img width="1440" alt="Bildschirmfoto 2020-11-12 um 11 51 52" src="https://user-images.githubusercontent.com/2178466/98931219-0929b500-24de-11eb-8493-3a1feb0f1097.png">
**After**
<img width="1438" alt="Bildschirmfoto 2020-11-12 um 11 52 22" src="https://user-images.githubusercontent.com/2178466/98931232-0c24a580-24de-11eb-8fdb-dd82ff98e4f2.png">

**Comment by bastianallgeier** [comment]
Yeah, I'm constantly playing around with the gap between layouts. It's a difficult balance between available space and clarity. But I guess clarity should be king here.

**Comment by Werbschaft** [comment]
Yes that is really difficult! From a purely visual point of view, I like the layout better without gaps, but I think it's clearer with gaps.

**Comment by bastianallgeier** [comment]
It also massively depends on the content. If you work a lot with wysiwyg blocks, the gaps are not that great. I will try a few more things

**Comment by bastianallgeier** [comment]
I think the last version really fixes the visual issues with this. The distances are the same as before, but the border is darker now and with the layout toolbar on the right, each layout is really easy to differentiate now.
