### ISSUE TITLE
Remove ellipsis

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#41]
Wouldn't the layout look cleaner if 3 dots were not shown after each block by default? My suggestion: if there is no name for the block then nothing will be displayed.

<img width="354" alt="Bildschirmfoto 2020-11-12 um 11 57 47" src="https://user-images.githubusercontent.com/2178466/98931590-81907600-24de-11eb-83c5-702bc030e29e.png">
<img width="313" alt="Bildschirmfoto 2020-11-12 um 11 59 05" src="https://user-images.githubusercontent.com/2178466/98931592-82c1a300-24de-11eb-902a-fe9f6be4733c.png">

**Comment by bastianallgeier** [comment]
✅
