### ISSUE TITLE
List snippet broken

### ISSUE THREAD

**Issue by rasteiner** [getkirby/blocks#58]
Since alpha 10 the list snippet doesn't match the list block definition yml anymore. 
One uses the [field name "list"](https://github.com/getkirby/kirby/blob/feature/blocks/blocks/list/list.php), the other the [field name "text"](https://github.com/getkirby/kirby/blob/feature/blocks/blocks/list/list.yml#L6). 

In alpha 9 both used the name `"list"`.

**Comment by bastianallgeier** [comment]
✅
