### ISSUE TITLE
Migrating content created with Kirby Builder Plugin to the new Blocks field?

### ISSUE THREAD

**Issue by mynameisfreedom** [getkirby/blocks#67]
Is it possible to migrate content created with Kirby Builder Plugin to the new Blocks field?

**Comment by mynameisfreedom** [comment]
**Update:** Most of the content is updated properly, but some blocks aren't. Will make more testing and look into the reasons.

**Comment by bastianallgeier** [comment]
Yes, please let me know which blocks fail to import properly. Normally, it should all work out of the box.

**Comment by bastianallgeier** [comment]
I close this for now. Feel free to open individual issues for blocks that cannot be imported.
