### ISSUE TITLE
Layout field improvement ideas

### ISSUE THREAD

**Issue by mynameisfreedom** [getkirby/blocks#68]
In the beginning just to say that the Layout field is great, it is a fantastic direction of development. 💪

But to become super ultra great, it could use a bit more extending. 

**Some would-be-great features for the future:**
- 1/5 and 1/6 widths
- Option to change column width on the fly if needed (from inside the column)
- **Nested layout field** would be ultra great

Maybe this will inspire some new ideas. 

Thank you for the work so far!

**Comment by bastianallgeier** [comment]
Would you be able to split this issue into three? One for the additional column widths, one for the option to change column widths afterwards and one for the nested layouts? Otherwise it will be super hard to keep track of the individual wishes.

**Comment by mynameisfreedom** [comment]
Hi, Bastian! Yes, of course, I'll do it later today.

**Comment by mynameisfreedom** [comment]
This issue is split into these three #73 - #74 - #75
