### ISSUE TITLE
writer field html showing as plain text inside structure 

### ISSUE THREAD

**Issue by igregson** [getkirby/blocks#83]
![image](https://user-images.githubusercontent.com/2054975/100779231-ed1e8280-33bc-11eb-89f8-b707067ab734.png)

![image](https://user-images.githubusercontent.com/2054975/100778914-784b4880-33bc-11eb-9f6c-3fda77f56e81.png)

**Comment by afbora** [comment]
Thanks for report. This issue already reported by @distantnative  https://github.com/getkirby/kirby/issues/2958
