### ISSUE TITLE
Drawer's "Close" icon resembles "Cancel" action

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/blocks#84]
The icon used for the "Close" button of the drawer is otherwise used consistently for "Cancel" across the Panel UI.

![Screenshot from 2020-12-02 08-56-24](https://user-images.githubusercontent.com/6355217/100844645-6d57ed00-347c-11eb-82ae-9b1d569a2372.png)

Other than with the Panel's regular modals, the drawer does not have a OK/Cancel choice, but instead is merely an extension of the main view (hence "Revert/Save" of the main view apply).

Could the `collapse` icon be appropriate instead?

**Comment by bastianallgeier** [comment]
Good point! collapse could work. I will give it a try.

**Comment by bastianallgeier** [comment]
✅
