### ISSUE TITLE
Files are not visible in section with files inside a tab

### ISSUE THREAD

**Issue by kaloja** [getkirby/blocks#86]
The error came with 1.0.0-alpha.13.

**1.0.0-alpha.12**
![Skärmavbild 2020-12-02 kl  10 54 44](https://user-images.githubusercontent.com/6732058/100857531-10186780-348d-11eb-859a-7dec6a75174f.png)

**1.0.0-alpha.13**
![Skärmavbild 2020-12-02 kl  10 55 11](https://user-images.githubusercontent.com/6732058/100857509-0858c300-348d-11eb-826a-bcd7aaf0cd76.png)

**Comment by bastianallgeier** [comment]
Please upgrade to the latest RC: https://github.com/getkirby/kirby/releases/tag/3.5.0-rc.2 We fixed it there.
